# Generated by Django 5.1.2 on 2024-10-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='data_admissão',
            new_name='data_admissao',
        ),
    ]
