# Generated by Django 5.1.2 on 2024-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservicos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicos',
            name='situacao',
            field=models.CharField(choices=[('A', 'Agendado'), ('C', 'Cancelado'), ('B', 'Realizado')], default='A', max_length=1, verbose_name='Situação'),
        ),
    ]
