# Generated by Django 5.1.2 on 2024-11-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservicos', '0002_alter_ordemservicos_situacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservicos',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='ordemservicos',
            name='constraint_agendamento',
        ),
    ]
