# Generated by Django 5.1.2 on 2024-11-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservicos', '0003_alter_ordemservicos_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicos',
            name='situacao',
            field=models.CharField(choices=[('B', 'Realizado'), ('A', 'Agendado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Situação'),
        ),
    ]
