# Generated by Django 5.1.2 on 2024-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservicos', '0003_alter_ordemservicos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicos',
            name='situacao',
            field=models.CharField(choices=[('C', 'Cancelado'), ('A', 'Agendado'), ('B', 'Realizado')], default='A', max_length=1, verbose_name='Situação'),
        ),
    ]
