# Generated by Django 5.1.2 on 2024-11-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservicos', '0004_alter_ordemservicos_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicos',
            name='situacao',
            field=models.CharField(choices=[('B', 'Realizado'), ('C', 'Cancelado'), ('A', 'Agendado')], default='A', max_length=1, verbose_name='Situação'),
        ),
    ]
