# Generated by Django 5.1.2 on 2024-11-19 17:08

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('produtosservico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do servico', max_length=100, unique='True', verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do servico', max_digits=5, verbose_name='Preço')),
                ('descricao', models.TextField(help_text='Descrição e observações do serviço', max_length=300, verbose_name='Descrição')),
                ('produto', models.ManyToManyField(through='produtosservico.ProdutosServico', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
        ),
    ]
